export const GET_ALL_CARDS_PENDING = 'GET_ALL_CARDS_PENDING';
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS';
export const GET_ALL_CARDS_ERROR = 'GET_ALL_CARDS_ERROR';

export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR';