export const GET_ALL_CARDS_PENDING = 'GET_ALL_CARDS_PENDING';
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS';
export const GET_ALL_CARDS_ERROR = 'GET_ALL_CARDS_ERROR';

export const DELETE_CARD_BY_ID_PENDING = 'DELETE_CARD_BY_ID_PENDING';
export const DELETE_CARD_BY_ID_SUCCESS = 'DELETE_CARD_BY_ID_SUCCESS';
export const DELETE_CARD_BY_ID_ERROR = 'DELETE_CARD_BY_ID_ERROR';

export const SET_COUNTER_CARDS_VALUE = 'SET_COUNTER_CARDS_VALUE';
export const SET_INIT_FALSE_VALUE = 'SET_INIT_FALSE_VALUE';