export const GET_ALL_CARDS_PENDING = 'GET_ALL_CARDS_PENDING';
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS';
export const GET_ALL_CARDS_ERROR = 'GET_ALL_CARDS_ERROR';
export const DELETE_CARD_BY_ID_SUCCESS = 'DELETE_CARD_BY_ID_SUCCESS';
export const SET_COUNTER_CARDS_VALUE = 'SET_COUNTER_CARDS_VALUE';
export const TOGGLE_THEME = 'TOGGLE_THEME';